#!/bin/sh

set -u

[ "$#" -ne 2 ] && {
  echo "Usage: $(basename "$0") SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]" 1>&2
  exit 1
}

SOURCE_IMAGE_TAG="$1"
TARGET_IMAGE_TAG="$2"
IS_DOCKER_HUB_AVAILABLE="$(if [ -z ${DOCKER_USERNAME+foo} ]; then
                             echo 'false'
                           else
                             echo 'true'
                           fi)"

if [ "${IS_DOCKER_HUB_AVAILABLE}" = true ]; then
  # Avoid a warning from docker login by using --password-stdin.
  echo "${DOCKER_PASSWORD}" \
    | docker login --username="${DOCKER_USERNAME}" --password-stdin \
  && docker tag "${SOURCE_IMAGE_TAG}" "${TARGET_IMAGE_TAG}" \
  && docker push "${TARGET_IMAGE_TAG}"
fi
